# Abdominal Aortic Aneurysms (AAA) {#aaa}

The aim of this risk calculator is to assist in decision making process of management of patients with asymptomatic infrarenal or juxtarenal aortic aneurysms found incidentally or through screening electively.

## Input variables

### Age

This describes the expected age of the patient at the time of the procedure. This is likely the same age as the patient at the time of the evaluation.

### Sex

This describes the documented sex or gender of the patient as recorded in the medical chart.

### Maximal Aortic Diameter

This is the maximal aortic diameter in the AP direction reported in mm.

### Patient Symptoms

Patient symptoms are stratified into asymptomatic, meaning that the patient has no clinical manifestations of aneurysm disease and the aneurysm was detected from screening, routine physical exam finding of pulsatile mass or incidentally. Symptomatic is defined as pain or tenderness associated with the abdominal aneurysm and concerning findings on imaging, requiring urgent intervention. Rupture is defined as patients presenting with acute onset of pain with or without hypotension and imaging findings concerning for aneurysm rupture.

### Renal Clamp

This describes whether the surgeon expects to clamp above both renal arteries in order to safely complete an open aortic aneurysm repair. Eslami et al includes use of a suprarenal clamp in their model for calculating in hospital mortality.\@eslami2015 There may be some differences in expected or actual utilization of a suprarenal clamp.

### Prior Aortic Surgery

This includes previous endovascular or open aortic surgery. Eslami et al do not describe explicitly what is included in this variable, but is it used as an exclusion criterion in their model, so we therefore, capture it here to ensure the model is not utilized inappropriately for these patients. @eslami2015

### History of Coronary Artery Disease

This describes whether the patient has a documented history of coronary artery disease(CAD). This is further subdivided into asymptomatic heart disease or unstable/symptomatic heart disease within the past 6 months. Not all models include this subdivision, so asymptomatic and symptomatic disease are often combined when included in models that treat CAD as a binary variable.

### Congestive Heart Failure

This describes whether a patient has documented congestive heart failure in their medical record.

### Stress Test

This describes whether a patient has undergone a preoperative cardiovascular stress test and the result of this test. If a patient has not undergone a stress test, then the user should select "Not Performed." The model should then be updated once the result of this test is known. Seeing how the result of this test changes the predictions related to post-operative myocardial infarction may help to determine whether this test is indicated for this specific patient.

### Cerebrovascular Disease

This describes whether a patient has had a previous cebrovascular event, such as a TIA or stroke.

### Chronic Obstructive Pulmonary Disease (COPD)

This describes whether a patient has a documented history of COPD. This is further subdivided into whether the patient is on medications or whether they require home oxygen therapy.

### Diabetes

This describes whether a patient has documented diabetes. This is further subdivided into whether their diabetes is controlled with diet, non-insulin medications or requires insulin. This variable does not distinguish Type 1 from Type 2 diabetes, however patients with Type 1 diabetes will likley fall into the category of diabetes requiring insulin therapy.

### ESRD

This describes patients with end stage renal disease (ESRD) requiring dialysis, whether peritoneal(PD) or hemodialysis(HD). Patients with ESRD on HD are included in the highest Cr or lowest eGFR category when considering renal function for those models that use these variables alone without explicitly asking whether a patient is on dialysis.

### Creatinine (mg/dL)

This describes the most recently collected creatinine level. This is not used for predictions in patients with end stage renal disease on dialysis. Cr, age, gender and race are utilized to calculate eGFR for those models that utilize this instead of creatinine alone.

## Annual Rupture Risk

The reported annual rupture risk is determined through a table published in the most recent edition of Rutherford's Vascular Surgery and Endovascular Therapy. @tracciAortoiliacAneurysmsEvaluation The data regarding rupture risk is not well established and is from a number of years ago. These rates vary across a number of publications without clear citation of the primary data source. We have color-coded the calculated annual rupture risk, based on expected clinical implications of the score.

## In-hospital Postprocedural Mortality

The model used for this risk prediction comes from the Vascular Study Group of New England (VSGNE) published in 2015. @eslami2015 There are a number of models for post-operative mortality, however they were not developed or validated in our target population specifically.[@meguidSurgicalRiskPreoperative2016d; @meguidSurgicalRiskPreoperative2016c; @meguidSurgicalRiskPreoperative2016e] We opted for a risk model developed specifically for elective aortic surgery.<br />

The outcome of interest was in-hospital postprocedural mortality. The patient cohort includes 4,431 patients who underwent elective AAA repair at institutions in Northeastern states on the United States of America (USA) captured in the prospectively collected VSGNE database between 2003 and 2013. This data was collected and maintained by trained nurse and clinical abstractors. The study excluded patients admitted for non-elective AAA repair, who had prior aortic surgery, or those who required a supraceliac clamp, so prediction scores are not available for these patients. <br />

The Model was developed using multivariable logistic regression with backward elimination, setting the alpha=0.2. The sum of the beta estimates was as follows:<br />

Sum of β- estimates= {-6.76+ 1.08 (IR AAA) +1.905 (SR AAA)+ 0.78 (Age≥75) +0.69 (Female)+0.56 (MCD)+0.71(CVD)+ 0.95(COPD) 0.89 (1.5≤Cr\<2)+1.31(Cr≥2)+0.91(AAA>6.5 cm)}<br />

The authors reported good discrimination of their score with an AUC 0.822. The authors found their score to have better discrimination, when compared to previously published models: GAS (AUC 0.685), Medicare (AUC 0.769) and VGNW (AUC 0.767) models. Three additional previously published models were not compared as they included variables not collected by the VSGNE database. The improved discrimination and rigorous data collection in a vascular surgery specific patient population is why we have included this model in our risk score instead of these previously developed models.<br/>

We have used this model to provide three prediction values in order to assist with decision making around which elective procedure to offer a patient presenting for evaluation. The first describes the mortality prediction, assuming that the patient underwent endovascular repair. The second describes the mortality prediction, assuming the patient underwent an open infrarenal repair. This open prediction is substituted for a third prediction, if the user signifies that they anticipate needing a suprarenal clamp for the repair. We have also considered patients who have ESRD on dialysis to be included in the group with Cr \> 2, although this variable assignment is not explicitly stated by the authors. We have color-coded the prediction to align with the authors' identified clinical cut points at \<1% for low risk (green), 1-8% for moderate risk (yellow), 8-30% for high risk (orange), and \>30% for prohibitive risk.<br />

The authors and our VasCalc have identified a number of limitations. The outcome of interest is in-hospital mortality, which means that this only applies to the index hospitalization. Also, as of now this model has not been externally validated on data collected outside the development registry. Additional variables that may include model discrimination include patient functional status, aortic anatomic characteristics, and center/surgeon volume.

## Post Operative In-hospital Myocardial Infarction

The model used to derive post operative in-hopsital myocardial infarction was published by Bertges et al in 2016. @bertgesVascularQualityInitiative2016

The outcome of interest is in-hospital post-operative myocardial infarction defined as troponin elevation alone or by clinical or ECG criteria. They deliberately did not include a composite end point of postoperative CHF or arrhythmia.

The population used to derive this model non-emergent vascular procedures in the Vascular Quality Initiative (VQI) registry performed between 2012 and 2014 (N=88,791 patients) and validated on procedures performed between 2015 and 2016 (N=27,555 patients). The VQI registry is composed of 350 community and academic hospitals in the United States and Canada. Procedures included in this population fell into 5 major categories, carotid endarterectomy, infra-inguinal revascularization, suprarenal revascularization, endovascular aortic aneurysm repair and open aortic aneurysm repair.

The authors excluded aneurysms involving the renal arteries. Therefore we are unable to calculate the risk score if the clinician inputs that they expect to need to clamp above the renal arteries. The authors also included only elective or emergent procedures without rupture. Therefore we excluded patients with ruptured aneurysms.

The authors developed this model using a bootstrapped logistic regression with step-wise variable elimination. The authors include models specific to EVAR and open AAA repair, however they only report odds ratios and not the full model. Therefore we based our predictions on the over all model which is reported in full. The sum of the beta coefficients is as follows:

Sum of β- estimates= {-5.82+ 0.17(EVAR) +1.91(OAAA)+ 0.44(Age 60-69) + 0.64(Age 70-79) + 1.10(Age \>=80) + 0.76(Cr \>=1.18) + 0.64(On Dialysis) - 0.15(Normal Stress Test) + 0.46(Abnormal Stress Test) + 0.40(Asymp CAD) + 0.76(Symp CAD) + 0.18(Diet controlled DM) + 0.20(Non insulin DM) + 0.39(Insulin DM) + 0.44(Asymp CHF) + 0.50(Symp CHF)}

The authors report good external validation with an AUC 0.75. While the authors did not specifically validate against other cardiac risk scores. They identify that many others are developed in a much broader surgical population and may not be as accurate when applied to a vascular surgery specific population particularly when stratifying across different vascular procedures. [@bertgesVascularStudyGroup2010; @guptaDevelopmentValidationRisk2011a]

The authors and our VasCalc group have identified a number of limitations. The authors report procedure specific models, however do not provide the full regression equation, therefore we are unable to use them here. The authors also report that this model is not intended to be used in the emergent situation, however symptomatic and urgent procedures are included in their cohort of patients. Finally, they include troponin-only definition of myocardial infarction. They report that troponin elevation is associated with poor outcomes, but the mechanism is not well understood and this definition and clinical relevance is controversial. Finally the AUC, while adequate is on the lower end of providing useful discrimination. Additional metrics for calibration might help to better compare this risk model to other published models.
