---
title: "Manual for Risk Prediction in Vascular Surgery"
author: "Adam Johnson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: references.bib
csl: jvs.csl
url: https://adam-mdmph.github.io/Risk-Prediction-Text/
description: |
  This manual is meant as an explanatory text to support the risk tool available at www.vascalc.org.
link-citations: yes
github-repo: https://github.com/adam-mdmph/Risk-Prediction-Text
---

# About

This manual is intended as an explanatory text to support the risk tools available at www.vascalc.org.

## Usage

Each chapter reflects a clinical scenario to which each of the the risk tools can be used to aid managment decision making can be applied. Each chapter will be broken down into sections that will outline the criteria used in the model, decision making rationale, and available evidence used to produce each presented risk prediction. This risk calculator is developed for the sole purpose of decision support and results should not superscede clinician and patient preference. The published evidence and risk prediction tools that have been used to create this resource are referenced and can be found here (insert reference hyperlink?)

The main purpose of this project is to bring together many models developed by different stakeholders and datasets into a single clinically relevant interface. Each patient, procedure and clinical outcome are associated according to unique characteristics. Some have attempted to develop broadly applicable risk models.[@meguidSurgicalRiskPreoperative2016c; @meguidSurgicalRiskPreoperative2016d; @meguidSurgicalRiskPreoperative2016e] However, it seems unlikely that developing a small number of widely applicable models will provide the nuance and predictive accuracy to provide patient level guidance to affect clinical decision making.

## Methods

The multivariable prognostic prediction models included in this project were found through a literature search of available medical databases, citation index review, and referrals from content experts. Published algorithms were reviewed and included if they met the following inclusion criteria:

1.  Input variables available and commonly collected in the pre-operative setting.
2.  Outcome variable relevant to clinician and patient for decision making.
3.  Full regression model with beta coefficients and intercept publicly available in publication or through contact with publication authors.

Available risk models were then reviewed and included based on their quality. Quality of risk model was determined according to published TRIPOD guidelines,[@collinsTransparentReportingMultivariable2015; @moonsTransparentReportingMultivariable2015] prioritizing the following values:

1.  Clearly described homogeneous patient population that aligns with the clinical question.
2.  Model performance assessments of discrimination and calibration (such as AUC, Hosmer-Lemeshow, Brier score, sensitivity or specificity) determined through internal and ideallyx external validation.
3.  Parsimonious input variable selection and clear description of variable definitions and manipulations.
4.  Transparent stakeholder engagement and algorithm development.

## Feedback

For suggestions, comments or questions please submit an issue on our [github page](https://github.com/adam-mdmph/vascalc/issues) or [send us an email](mailto:vascularcalculator@gmail.com).

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'flexdashboard', 'finalfit'
), 'packages.bib')
```
